datasets:
  - name: wikidata-movie-descriptions
    output: data/
    source:
      type: sparql-query
      default_field_type: text
      endpoint: https://qlever.dev/api/wikidata-sebastian
      query: |
        PREFIX wikibase: <http://wikiba.se/ontology#>
        PREFIX schema: <http://schema.org/>
        PREFIX wd: <http://www.wikidata.org/entity/>
        PREFIX wdt: <http://www.wikidata.org/prop/direct/>
        SELECT ?item ?abstract WHERE {
          ?item wdt:P31/wdt:P279* wd:Q11424 .
          ?item ^schema:about/schema:description ?abstract .
          FILTER (LANG(?abstract) = "en")
          ?item ^schema:about/wikibase:sitelinks ?sitelinks
        }
        ORDER BY DESC(?sitelinks) DESC(?item)
        LIMIT 10000
      format: json

models:
  - name: text-embedding
    type: vllm
    endpoint: http://localhost:8000
    model_name: mixedbread-ai/mxbai-embed-xsmall-v1

embeddings:
  - name: wikidata-movies-embeddings
    model: text-embedding
    output: data/embeddings.safetensors
    data: data/
    batch_size: 128

indices:
  - name: wikidata-movies-full-text
    description: Full-text search over Wikidata movie descriptions
    type: full-text
    data: data/
    output: index/full-text/
  - name: wikidata-movies-embedding
    description: Semantic search over Wikidata movie descriptions
    type: embedding-with-data
    data: data/
    embedding_data: data/embeddings.safetensors
    output: index/embedding/
    model: text-embedding

server:
  host: 0.0.0.0
  port: 8080
  cors: true
  indices:
    - wikidata-movies-full-text
    - wikidata-movies-embedding
